USB_VID = 0x303A
USB_PID = 0x8244
USB_PRODUCT = "Barduino 4.0.2"
USB_MANUFACTURER = "Fablab Barcelona"

IDF_TARGET = esp32s3

CIRCUITPY_ESP_FLASH_MODE = qio
CIRCUITPY_ESP_FLASH_FREQ = 80m
CIRCUITPY_ESP_FLASH_SIZE = 8MB
CIRCUITPY_ESPCAMERA = 0
