USB_VID = 0x2e8a
USB_PID = 0x109a
USB_PRODUCT = "Challenger+ RP2350 WiFi6/BLE5"
USB_MANUFACTURER = "Invector Labs"

CHIP_VARIANT = RP2350
CHIP_PACKAGE = A
CHIP_FAMILY = rp2

EXTERNAL_FLASH_DEVICES = "W25Q64JVxQ"

CIRCUITPY__EVE = 1
CIRCUITPY_ALARM = 0

FROZEN_MPY_DIRS += $(TOP)/frozen/Adafruit_CircuitPython_HID
FROZEN_MPY_DIRS += $(TOP)/frozen/Adafruit_CircuitPython_Register
